// Generated by CoffeeScript 1.6.2
var _base, _ref,
  __slice = [].slice;

if ((_ref = (_base = Array.prototype).seq) == null) {
  _base.seq = function() {
    var args, cb, e, func, idx, next,
      _this = this;

    func = arguments[0], idx = arguments[1], cb = arguments[2], args = 4 <= arguments.length ? __slice.call(arguments, 3) : [];
    if (idx instanceof Function) {
      cb = idx;
      idx = 0;
    }
    if (idx >= this.length) {
      return cb.apply(this, [void 0].concat(args));
    }
    next = function() {
      var a;

      if (arguments[0] instanceof Error) {
        return cb(arguments[0]);
      }
      return Array.prototype.seq.apply(_this, [func, idx + 1, cb].concat((function() {
        var _i, _len, _results;

        _results = [];
        for (_i = 0, _len = arguments.length; _i < _len; _i++) {
          a = arguments[_i];
          _results.push(a);
        }
        return _results;
      }).apply(_this, arguments)));
    };
    try {
      return func.apply(this, [this[idx], idx, next].concat(args));
    } catch (_error) {
      e = _error;
      return cb(e);
    }
  };
}
