"use strict";

// Generated by CoffeeScript 2.2.4
var base;

if ((base = Array.prototype).seq == null) {
  base.seq = function () {
    var _arguments2 = arguments,
        _this = this;

    var args, cb, e, func, idx, next;

    var _arguments = Array.prototype.slice.call(arguments);

    func = _arguments[0];
    idx = _arguments[1];
    cb = _arguments[2];
    args = _arguments.slice(3);

    if (idx instanceof Function) {
      cb = idx;
      idx = 0;
    }
    if (idx >= this.length) {
      return cb.apply(this, [void 0].concat(args));
    }
    next = function next() {
      var a;
      if (_arguments2[0] instanceof Error) {
        return cb(_arguments2[0]);
      }
      return Array.prototype.seq.apply(_this, [func, idx + 1, cb].concat(function () {
        var i, len, results;
        results = [];
        for (i = 0, len = arguments.length; i < len; i++) {
          a = arguments[i];
          results.push(a);
        }
        return results;
      }.apply(_this, _arguments2)));
    };
    try {
      return func.apply(this, [this[idx], idx, next].concat(args));
    } catch (error) {
      e = error;
      return cb(e);
    }
  };
}