'use strict';

// Generated by CoffeeScript 2.2.4
$(function () {
  var getBox;
  getBox = function getBox(elem) {
    if (elem.parent().hasClass('item')) {
      return elem.parent();
    }
    return elem.parentsUntil('.item').parent().eq(0);
  };
  $('.item a').mouseenter(function () {
    return getBox($(this)).addClass('hover');
  }).mouseleave(function () {
    return getBox($(this)).removeClass('hover');
  });
  $('.products').masonry({
    itemSelector: '.item'
  }).masonry('reload', function () {
    var _this = this;

    var n;
    n = $(this).length;
    return function () {
      var results = [];
      for (var i = 1; 1 <= n ? i <= n : i >= n; 1 <= n ? i++ : i--) {
        results.push(i);
      }
      return results;
    }.apply(this).seq(function (item, idx, next) {
      $(_this).eq(idx).betterToggle();
      return function () {
        return setTimeout(function () {
          return next();
        }, 50);
      }();
    }, function (err) {});
  });
  if (!/localhost/.test(location.href)) {
    return $('.library .item').each(function (idx) {
      var _this2 = this;

      var repo;
      repo = $(this).find('h4').text().replace(/^\s+/, '').replace(/\s+$/, '');
      return $.ajax({
        url: 'https://api.github.com/repos/ktty1220/' + repo,
        dataType: 'jsonp',
        success: function success(json) {
          var ref;
          return $(_this2).find('.hubinfo .star').show().text((ref = json.data.watchers) != null ? ref : 0);
        }
      });
    });
  }
});